### ISSUE TITLE
关于下载路径的问题。

### ISSUE THREAD

**Issue by moyu-jun** [shanyao0/DownLoadManager#1]
如果我的文件下载路径是：http://aaa.com/apk/new_release.apk
请问应该如何进行下载？如果将此路径放在retrofit.baseUrl()里面，则会报错。
报错信息是URL需要以“/”结尾。
请问这个问题要如何去解决？感谢！

**Comment by shanyao0** [comment]
@dkylin <br>
一修改这里：<br>retrofit.baseUrl("http://aaa.com/apk/")<br>
二修改这里：<br>public interface IFileLoad {
          @ GET("new_release.apk")
        Call<ResponseBody> loadFile();
    }<br>
如果还有问题加我QQ：785137655

**Comment by moyu-jun** [comment]
@shanyao0 好的，我试试。谢谢。

**Comment by moyu-jun** [comment]
@shanyao0 已解决。谢谢

**Comment by dkylin** [comment]
@shanyao0 已解决。谢谢
